title: "HTeuMeuLeu"
url: "https://www.hteumeuleu.com"
description: "The homepage of french email developer Rémi Parmentier."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:year/:title/

plugins:
  - jekyll-mentions

sass:
  style: compressed

exclude: ["Gemfile", "Gemfile.lock", "CONTRIBUTING.md", "LICENSE", "README.md"]
include: ["_pages", "_redirects"]

#incremental: true